name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - stable
        - oldstable
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        cache: true
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libproj-dev
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        cache: true
        go-version: stable
    - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
      with:
        version: v1.55.2